# Generated by Django 5.2.8 on 2025-11-08 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional notes about the appointment.",
                        max_length=200,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["start_time"], name="appointment_start_t_fb73a8_idx"
                    ),
                    models.Index(fields=["email"], name="appointment_email_0ae08b_idx"),
                ],
            },
        ),
    ]
